# Generated by Django 5.2.7 on 2026-01-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Randevular', '0002_randevu_psychologist_user_psychologistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologistprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Uzmanlık Alanı'),
        ),
        migrations.AddField(
            model_name='psychologistprofile',
            name='university',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mezun Olduğu Üniversite'),
        ),
    ]
